// Generated by ts-to-zod
import { z } from "zod";

export const replaceSchema = z.object({
  src: z.string(),
  trg: z.string(),
  default: z.string().optional(),
});

export const configSchema = z.object({
  include: z.array(z.string()).optional(),
  exclude: z.array(z.string()).optional(),
  define: z.array(replaceSchema.omit({ src: true })).optional(),
  replaceInPath: z.array(replaceSchema).optional(),
  replaceInFile: z.array(replaceSchema).optional(),
});

export const templateKeySchema = z.any();
